# Generated by Django 4.2.3 on 2023-07-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('credit', models.IntegerField(default=15)),
                ('module_desc', models.TextField()),
                ('category', models.CharField(default='Compulsory', max_length=255)),
                ('availability', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(related_name='modules', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('module_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereg.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
